site_url: !ENV [SITE_NAME, 'http://kb.barraider.com']
# site_url: http://cyberlightdev.github.io 
site_name: BarRaider's Knowledge Base
markdown_extensions:
  - admonition # Fancy callouts (https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition-icons)
  - pymdownx.details # Collapsible callouts
  - pymdownx.superfences # Nest Markdown in callouts (https://facelessuser.github.io/pymdown-extensions/extensions/superfences/)
  - pymdownx.keys # Render Keyboard keys with markdown (https://facelessuser.github.io/pymdown-extensions/extensions/keys/)
  - md_in_html # Currently we're using this for image captions
  - pymdownx.tasklist: # Support for Tabs (https://fabacademy.org/2022/labs/kannai/Instruction/tips/tab_in_markdown/)
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
   #- attr_list
plugins:
  - search
  - glightbox #fancy image zoom (https://github.com/blueswen/mkdocs-glightbox#usage)
  - mkdocs-video
theme:
  name: "material"
  logo: "img/barraider-logo2.png"
  features:
    - navigation.instant      # Makes it act like a Single-Page Application
    - navigation.tabs         # Top-Level Nav is rendered in the top
    #- navigation.tabs.sticky  # and scrolls with the page on longer pages
    #- navigation.expand      # Show  sub-sections in left pane
    - navigation.indexes      # Simpler Nav for sub-sections with overview pages
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra:
  logo: img/barraider-logo.avif
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/realBarRaider
    - icon: fontawesome/brands/discord
      link: http://discord.barraider.com/
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/barraider
      name: Support BarRaider's Work on Patreon
    - icon: fontawesome/brands/github
      link: https://github.com/BarRaider
