INHERIT: base.yml
nav:
  - 'Plugin FAQs':
    - 'index.md' # Hidden on the menu, accessed when clicking "Plugin FAQs"
    - 'General Issues': 'faqs/general/index.md'
    - 'API Ninja': 'faqs/api-ninja/index.md'
    - 'Battery':
      - 'CORSAIR iCue': 'faqs/battery/icue.md'
      - 'Logitech G HUB': 'faqs/battery/ghub.md'
    - 'OBS Tools':
      - 'Getting Started': 'faqs/obs-tools/getting-started.md'
      - 'Available Actions': 'faqs/obs-tools/actions.md'
      - 'Troubleshooting': 'faqs/obs-tools/troubleshooting.md'
    - 'Spotify':
      - 'Getting started': 'faqs/spotify/getting-started.md'
      - 'Troubleshooting': 'faqs/spotify/troubleshooting.md'
    - 'SuperMacro':
      - 'Getting started': 'faqs/supermacro/getting-started.md'
      - 'Advanced Settings explained': 'faqs/supermacro/advanced-settings.md'
      - 'Avaliable Actions': 'faqs/supermacro/actions.md'
      - 'Usage Examples': 'faqs/supermacro/examples.md'
      - 'Commands': 'faqs/supermacro/commands.md'
      - 'Functions': 'faqs/supermacro/functions.md'
      - 'Loops': 'faqs/supermacro/loops.md'
      - 'Variables': 'faqs/supermacro/variables.md'
    - 'VoiceMeeter':
      - 'Getting Started': 'faqs/voicemeeter/getting-started.md'
      - 'Available Actions': 'faqs/voicemeeter/actions.md'
      - 'Usage Examples': 'faqs/voicemeeter/examples.md'
    - 'Windows Mover & Resizer':
      - 'Getting Started': 'faqs/win-mover-resizer/getting-started.md'
      - 'Troubleshooting': 'faqs/win-mover-resizer/troubleshooting.md'
  - Discord: http://discord.barraider.com
