INHERIT: base.yml
nav:
  - 'Plugin FAQs':
    - 'index.md' # Hidden on the menu, accessed when clicking "Plugin FAQs"
    - 'API Ninja': 'faqs/api-ninja/index.md'
    - 'OBS Tools':
      - 'Getting Started': 'faqs/obs-tools/getting-started.md'
      - 'Available Actions': 'faqs/obs-tools/actions.md'
      - 'Troubleshooting': 'faqs/obs-tools/troubleshooting.md'
    - 'Spotify':
      - 'Getting started': 'faqs/spotify/getting-started.md'
      - 'Troubleshooting': 'faqs/spotify/troubleshooting.md'
    - 'SuperMacro':
      - 'Avaliable Actions': 'faqs/SuperMacro/actions.md'
      - 'Usage Examples': 'faqs/SuperMacro/usage-examples.md'
      - 'Commands': 'faqs/SuperMacro/commands.md'
  - Discord: http://discord.barraider.com
